In [1]:
import helper
data_dir='moes_tavern_lines.txt'
text=helper.load_data(data_dir)
print (text)
print ('=============================================================')
# ignore notice
text=text[81:]
print (text)

[YEAR DATE 1989] © Twentieth Century Fox Film Corporation. All rights reserved.

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.


Moe_Szyslak: Ah, isn't that nice. Now, there is a politician who cares.
Barney_Gumble: If I ever vote, it'll be for him. (BELCH)


Barney_Gumble: Hey Homer, how's your neighbor's store doing?
Homer_Simpson: Lousy. He just

In [2]:
# data exploration
view_sentence_range=(0, 10)

import numpy as np
print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))
scenes=text.split('\n\n')
print('Number of scenes: {}'.format(len(scenes)))
sentence_count_scene=[scene.count('\n') for scene in scenes]
print('Average number of sentences in each scene: {}'.format(np.average(sentence_count_scene)))
sentences=[sentence for scene in scenes for sentence in scene.split('\n')]
print('Number of lines: {}'.format(len(sentences)))
word_count_sentence=[len(sentence.split()) for sentence in sentences]
print('Average number of words in each line: {}'.format(np.average(word_count_sentence)))
print()
print('The sentences {} to {}:'.format(*view_sentence_range))
print('\n'.join(text.split('\n')[view_sentence_range[0]:view_sentence_range[1]]))

Dataset Stats
Roughly the number of unique words: 11492
Number of scenes: 262
Average number of sentences in each scene: 15.251908396946565
Number of lines: 4258
Average number of words in each line: 11.50164396430249

The sentences 0 to 10:

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.



In [3]:
'''Lookup Table
To create a word embedding, first need to transform the words to ids. In this function, create two dictionaries:
Dictionary to go from the words to an id, we'll call vocab_to_int
Dictionary to go from the id to word, we'll call int_to_vocab'''
import numpy as np
import problem_unittests as tests
from collections import Counter
'''A Counter is a dict subclass for counting hashable objects. 
It is an unordered collection where elements are stored as dictionary keys 
and their counts are stored as dictionary values. Counts are allowed to be 
any integer value including zero or negative counts. The Counter class is 
similar to bags or multisets in other languages.'''
counter=Counter(text)
print (counter)
print (counter.keys())
vocab_to_int={word:idx for idx, word in enumerate(counter.keys())}
print (vocab_to_int)
int_to_vocab={idx:word for word, idx in vocab_to_int.items()}
print (int_to_vocab)

Counter({' ': 44978, 'e': 23343, 'o': 18615, 'a': 15055, 't': 14038, 'n': 13220, 's': 11557, 'r': 11512, 'i': 10922, 'h': 9096, 'l': 8890, 'm': 7350, 'y': 7105, 'u': 6710, '.': 6024, 'd': 5566, 'S': 4765, '\n': 4518, 'g': 4090, ':': 4054, '_': 3878, 'p': 3704, 'I': 3689, 'k': 3597, ',': 3574, 'w': 3395, 'c': 3337, "'": 2924, 'H': 2848, 'b': 2779, 'f': 2778, 'M': 2658, 'E': 2227, 'T': 2121, 'A': 1993, 'O': 1991, 'N': 1939, 'L': 1892, '(': 1550, ')': 1549, 'v': 1541, 'C': 1481, 'G': 1385, 'z': 1338, '!': 1242, 'R': 1230, 'B': 1219, 'D': 1128, 'W': 1120, '?': 1100, 'Y': 1082, 'U': 923, '-': 811, 'P': 697, 'F': 599, 'K': 484, '"': 418, 'j': 315, 'V': 261, 'J': 221, 'x': 219, '/': 145, 'q': 81, 'Z': 72, 'Q': 59, 'X': 55, '1': 19, '2': 15, '0': 14, '5': 14, '#': 13, 'Ã': 13, ';': 7, '7': 7, '9': 7, '3': 6, '4': 5, '8': 4, '6': 4, '©': 3, '€': 3, '&': 3, '¼': 2, '£': 1, '$': 1, '%': 1, '\xa0': 1, '³': 1, '¨': 1, '¤': 1})
dict_keys(['Q', 'W', 'c', 'i', '\n', 'E', 'l', '3', 'p', 'R', ',', '4', 

In [7]:
def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts (vocab_to_int, int_to_vocab)
    """
    counter=Counter(text)
    vocab_to_int={word:idx for idx, word in enumerate(counter.keys())}
    int_to_vocab={idx:word for word, idx in vocab_to_int.items()}
    return vocab_to_int, int_to_vocab
    
# test
tests.test_create_lookup_tables(create_lookup_tables)

Tests Passed


In [6]:
# Tokenize Punctuation
'''Implement the function token_lookup to return a dict that will be used to tokenize symbols like "!" into "||Exclamation_Mark||". Create a dictionary for the following symbols where the symbol is the key and value is the token:
Period ( . )
Comma ( , )
Quotation Mark ( " )
Semicolon ( ; )
Exclamation mark ( ! )
Question mark ( ? )
Left Parentheses ( ( )
Right Parentheses ( ) )
Dash ( -- )
Return ( \n )
This dictionary will be used to token the symbols and add the delimiter (space) around it. This separates the symbols as it's own word, making it easier for the neural network to predict on the next word.'''
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenize dictionary where the key is the punctuation and the value is the token
    """
    token_dict = {'.' : '||period||',
                  ',' : '||comma||',
                  '"' : '||quotation_mark||',
                  ';' : '||semicolon||',
                  '!' : '||exclamation_mark||',
                  '?' : '||question_mark||',
                  '(' : '||left_parentheses||',
                  ')' : '||right_parentheses||',
                 '--' : '||dash||',
                 '\n' : '||return||'}
    return token_dict

# test
tests.test_tokenize(token_lookup)

Tests Passed


In [8]:
# Preprocess Training, Validation, and Testing Data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

In [9]:
# Load the data
int_text, vocab_to_int, int_to_vocab, token_dict=helper.load_preprocess()
print (int_text)
print (vocab_to_int)
print (int_to_vocab)
print (token_dict)

[5544, 4154, 1275, 2572, 6444, 2979, 6096, 5463, 3280, 5954, 379, 6298, 5233, 598, 158, 3280, 5544, 3392, 3035, 6085, 4220, 6085, 3154, 6085, 3116, 6500, 353, 2699, 5560, 828, 6085, 1632, 3280, 5544, 4154, 1275, 2572, 6444, 2979, 5636, 5044, 6085, 2802, 4708, 3280, 1275, 598, 5168, 2979, 6500, 1632, 3280, 6500, 1632, 3280, 5493, 6085, 387, 267, 2083, 6500, 1632, 6085, 5846, 2699, 5544, 4154, 1275, 2572, 6444, 2979, 208, 1081, 4808, 4399, 3280, 5829, 244, 2416, 254, 6229, 742, 6756, 1081, 6085, 2552, 6229, 742, 1583, 2186, 828, 5044, 3402, 4203, 3875, 3808, 5575, 5524, 3280, 5544, 4154, 5749, 379, 5696, 825, 2699, 1385, 6313, 3402, 895, 4678, 4486, 3280, 5544, 3496, 95, 349, 2186, 6604, 6085, 1911, 3280, 1363, 2930, 3416, 5829, 3280, 5544, 4154, 825, 6085, 5493, 6085, 1081, 5790, 6313, 158, 598, 5096, 3402, 6604, 3280, 5544, 1622, 4220, 6085, 1081, 5790, 3503, 158, 598, 2620, 3402, 4759, 6338, 3280, 5544, 5544, 5544, 4154, 5315, 6085, 4531, 1337, 1011, 3280, 5170, 6085, 353, 3116, 2244,

In [10]:
# RNN implementation
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# check tensorflow version
assert LooseVersion(tf.__version__)>=LooseVersion('1.0'), 'please use TensorFlow version 1.0 or newer'
print ('TensorFlow Version: {}'.format(tf.__version__))

# check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found')
else:
    print ('Default GPU Device: {}'.format(tf.test.gpu_device_name()))

TensorFlow Version: 1.0.1


c:\python35\lib\site-packages\ipykernel_launcher.py:12: UserWarning: No GPU found
  if sys.path[0] == '':


In [11]:
# create TF Placeholders for the Neural Network
def get_inputs():
    inputs=tf.placeholder(tf.int32, [None, None], name='input')
    targets=tf.placeholder(tf.int32, [None, None], name='targets')
    learning_rate=tf.placeholder(tf.float32, name='learning_rate')
    return inputs, targets, learning_rate

#test
tests.test_get_inputs(get_inputs)

Tests Passed


In [12]:
# build RNN
def get_init_cell(batch_size, rnn_size):
    """
    Create an RNN Cell and initialize it.
    :param batch_size: Size of batches
    :param rnn_size: Size of RNNs
    :return: Tuple (cell, initialize state)
    """
    # The Rnn size should be set using rnn_size
    #Args:
    #num_units: int, The number of units in the LSTM cell.
    #forget_bias: float, The bias added to forget gates (see above).
    #input_size: Deprecated and unused.
    lstm=tf.contrib.rnn.BasicLSTMCell(rnn_size)
    lstm_drop=tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=0.6)
    rnn_cell=tf.contrib.rnn.MultiRNNCell([lstm_drop]*2)   # two layers
    initial_state=rnn_cell.zero_state(batch_size, tf.float32)
    # Return zero-filled state tensor(s).---[batch_size x state_size]
    initial_state=tf.identity(initial_state, name='initial_state')
    # Return a Tensor has the same type as input.
    
    #Return the cell and initial state
    return rnn_cell, initial_state

# test
tests.test_get_init_cell(get_init_cell)

Tests Passed


In [13]:
# Word Embedding
# Apply embedding to input_data using TensorFlow. Return the embedded sequence.
"""
Create embedding for <input_data>.
:param input_data: TF placeholder for text input.
:param vocab_size: Number of words in vocabulary.
:param embed_dim: Number of embedding dimensions
:return: Embedded input.
"""
def get_embed(input_data, vocab_size, embed_dim):
    # random_uniform(shape,minval=0,maxval=None,dtype=tf.float32,seed=None,name=None)
    embedding=tf.Variable(tf.random_uniform((vocab_size, embed_dim), -1, 1))
    embed=tf.nn.embedding_lookup(embedding, input_data)
    return embed

# test
tests.test_get_embed(get_embed)

Tests Passed


In [14]:
# build RNN
'''Build the RNN using the tf.nn.dynamic_rnn()
Apply the name "final_state" to the final state using tf.identity()
Return the outputs and final_state state in the following tuple (Outputs, FinalState)'''
def build_rnn(cell, inputs):
    """
    Create a RNN using a RNN Cell
    :param cell: RNN Cell
    :param inputs: Input text data
    :return: Tuple (Outputs, Final State)
    """
    # cell: An instance of RNNCell.
    # inputs: The RNN inputs.
    # Returns: A pair (outputs, state) 
    outputs, final_state=tf.nn.dynamic_rnn(cell, inputs, dtype=tf.float32)
    final_state=tf.identity(final_state, name='final_state')
    return outputs, final_state

# test
tests.test_build_rnn(build_rnn)

Tests Passed


In [51]:
# build the model
#Apply embedding to input_data using get_embed(input_data, vocab_size, embed_dim) function.
#Build RNN using cell and build_rnn(cell, inputs) function.
#Apply a fully connected layer with a linear activation and vocab_size as the number of outputs.
#Return the logits and final state in the following tuple (Logits, FinalState)
def build_nn(cell, rnn_size, input_data, vocab_size):
    """
    Build part of the neural network
    :param cell: RNN cell
    :param rnn_size: Size of rnns
    :param input_data: Input data
    :param vocab_size: Vocabulary size
    :return: Tuple (Logits, FinalState)
    """
    embed=get_embed(input_data, vocab_size, rnn_size)
    outputs, final_state=build_rnn(cell, embed)
    logits=tf.contrib.layers.fully_connected(outputs, vocab_size, activation_fn=None)
    return logits, final_state

#test
tests.test_build_nn(build_nn)

Tests Passed


In [42]:
# batch test
n=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
batch_size=3
seq_len=4
batch_num=int(len(n)/batch_size/seq_len)
print (batch_num)

2


In [43]:
xdata = np.array(n[: batch_num * batch_size * seq_len])
print(xdata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [44]:
ydata = np.array(n[1: batch_num * batch_size * seq_len+1])
print(ydata)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [45]:
print (xdata.reshape(batch_size, -1))
print (ydata.reshape(batch_size, -1))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]]


In [46]:
# # numpy.split(ary, indices_or_sections, axis=0)
x_batches=np.split(xdata.reshape(batch_size, -1), batch_num, 1)
y_batches=np.split(ydata.reshape(batch_size, -1), batch_num, 1)
print (x_batches)
print (y_batches)

[array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]]), array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24]])]
[array([[ 2,  3,  4,  5],
       [10, 11, 12, 13],
       [18, 19, 20, 21]]), array([[ 6,  7,  8,  9],
       [14, 15, 16, 17],
       [22, 23, 24, 25]])]


In [64]:
print (np.array(list(zip(x_batches, y_batches))))
print ('=======')
print (np.array(list(zip(x_batches, y_batches)))[0][0])
print ('=======')
for batch_i, (x, y) in enumerate(np.array(list(zip(x_batches, y_batches)))):
    print ('x={}, y={}'.format(x, y))

[[[[ 1  2  3  4]
   [ 9 10 11 12]
   [17 18 19 20]]

  [[ 2  3  4  5]
   [10 11 12 13]
   [18 19 20 21]]]


 [[[ 5  6  7  8]
   [13 14 15 16]
   [21 22 23 24]]

  [[ 6  7  8  9]
   [14 15 16 17]
   [22 23 24 25]]]]
[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]]
x=[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]], y=[[ 2  3  4  5]
 [10 11 12 13]
 [18 19 20 21]]
x=[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]], y=[[ 6  7  8  9]
 [14 15 16 17]
 [22 23 24 25]]


In [24]:
def get_batches(int_text, batch_size, seq_length):
    """
    Return batches of input and target
    :param int_text: Text with the words replaced by their ids
    :param batch_size: The size of batch
    :param seq_length: The length of sequence
    :return: Batches as a Numpy array
    """
    batch_number=int(len(int_text)/batch_size/seq_length)
    xdata = np.array(int_text[: batch_number * batch_size * seq_length])
    ydata = np.array(int_text[1: batch_number * batch_size * seq_length+1])
    x_batches=np.split(xdata.reshape(batch_size, -1), batch_number, 1)
    y_batches=np.split(ydata.reshape(batch_size, -1), batch_number, 1)
    batches=list(zip(x_batches, y_batches))
    batches=np.array(batches)
    return batches

#test
tests.test_get_batches(get_batches)

Tests Passed


In [48]:
# RNN training
# hyperparameters
num_epochs=100   #number of epochs
batch_size=256  #size of batch
rnn_size=256   #size of rnn
seq_length=30    # length of sequence
learning_rate=0.01    #learning rate
show_every_n_batches=10   # show stats for every n number of batches

save_dir='./save'

In [53]:
# build the graph
from tensorflow.contrib import seq2seq

train_graph=tf.Graph()
with train_graph.as_default():
    vocab_size=len(int_to_vocab)
    input_text, targets, lr=get_inputs()
    input_data_shape=tf.shape(input_text)
    cell, initial_state=get_init_cell(input_data_shape[0], rnn_size)
    logits, final_state=build_nn(cell, rnn_size, input_text, vocab_size)
    
    # probabilities for generating words
    probs=tf.nn.softmax(logits, name='prob')
    
    #loss function
    # sequence_loss(logits,targets,weights,average_across_timesteps=True,average_across_batch=True,softmax_loss_function=None,name=None)
    cost=seq2seq.sequence_loss(logits, targets, tf.ones([input_data_shape[0], input_data_shape[1]]))
    #logits: A 3D Tensor of shape [batch_size x sequence_length x num_decoder_symbols] and dtype float. The logits correspond to the prediction across all classes at each timestep.
    #targets: A 2D Tensor of shape [batch_size x sequence_length] and dtype int. The target represents the true class at each timestep.
    #weights: A 2D Tensor of shape [batch_size x sequence_length] and dtype float. Weights constitutes the weighting of each prediction in the sequence. When using weights as masking set all valid timesteps to 1 and all padded timesteps to 0.
    
    #Optimazer
    optimizer=tf.train.AdamOptimizer(lr)
    
    # Gradient Clipping
    #tf.train.Optimizer.compute_gradients(loss, var_list=None, gate_gradients=1, aggregation_method=None, colocate_gradients_with_ops=False, grad_loss=None)
    #Return a list of (gradient, variable) pairs. Variable is always present, but gradient can be None.
    gradients=optimizer.compute_gradients(cost)
    #tf.clip_by_value(t, clip_value_min, clip_value_max, name=None)
    capped_gradients=[(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients]
    #tf.train.Optimizer.apply_gradients(grads_and_vars, global_step=None, name=None)
    train_op=optimizer.apply_gradients(capped_gradients)

In [54]:
# Train the neural network on the preprocessed data.
batches=get_batches(int_text, batch_size, seq_length)

# run(
#    fetches---A single graph element, a list of graph elements, or a dictionary whose values are graph elements or lists of graph elements 
#    feed_dict=None---A dictionary that maps graph elements to values
#    options=None---A [RunOptions] protocol buffer
#    run_metadata=None---A [RunMetadata] protocol buffer)

with tf.Session(graph=train_graph) as sess:
    sess.run(tf.global_variables_initializer())
    for epoch_i in range(num_epochs):
        state=sess.run(initial_state, {input_text: batches[0][0]})
        for batch_i, (x, y) in enumerate(batches):
            feed={input_text:x, targets:y, initial_state:state, lr:learning_rate}
            train_loss, state, _=sess.run([cost, final_state, train_op], feed)
            
            # show
            if (epoch_i*len(batches)+batch_i)%show_every_n_batches==0:
                print('Epoch {:>3} Batch {:>4}/{}  train_loss={:.3f}'.format(
                epoch_i, batch_i, len(batches), train_loss))
    
    #save
    saver=tf.train.Saver()
    saver.save(sess, save_dir)
    print ('model trained and saved')

Epoch   0 Batch    0/8  train_loss=8.822
Epoch   1 Batch    2/8  train_loss=6.223
Epoch   2 Batch    4/8  train_loss=6.005
Epoch   3 Batch    6/8  train_loss=5.997
Epoch   5 Batch    0/8  train_loss=5.995
Epoch   6 Batch    2/8  train_loss=5.918
Epoch   7 Batch    4/8  train_loss=5.784
Epoch   8 Batch    6/8  train_loss=5.723
Epoch  10 Batch    0/8  train_loss=5.651
Epoch  11 Batch    2/8  train_loss=5.575
Epoch  12 Batch    4/8  train_loss=5.405
Epoch  13 Batch    6/8  train_loss=5.361
Epoch  15 Batch    0/8  train_loss=5.314
Epoch  16 Batch    2/8  train_loss=5.271
Epoch  17 Batch    4/8  train_loss=5.161
Epoch  18 Batch    6/8  train_loss=5.088
Epoch  20 Batch    0/8  train_loss=5.018
Epoch  21 Batch    2/8  train_loss=4.962
Epoch  22 Batch    4/8  train_loss=4.833
Epoch  23 Batch    6/8  train_loss=4.762
Epoch  25 Batch    0/8  train_loss=4.746
Epoch  26 Batch    2/8  train_loss=4.725
Epoch  27 Batch    4/8  train_loss=4.615
Epoch  28 Batch    6/8  train_loss=4.567
Epoch  30 Batch 

In [57]:
# Save parameters (save seq_length and save_dir for generating a new TV script)
helper.save_params((seq_length, save_dir))

In [65]:
# load the data
import tensorflow as tf
import numpy as np
import helper
import problem_unittests as tests

_, vocab_to_int, int_to_vocab, token_dict=helper.load_preprocess()
seq_length, load_dir=helper.load_params()

In [69]:
# get tensors
def get_tensors(loaded_graph):
    
    """
    Get input, initial state, final state, and probabilities tensor from <loaded_graph>
    :param loaded_graph: TensorFlow graph loaded from file
    :return: Tuple (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    """
    # Get tensors from loaded_graph using the function get_tensor_by_name().
    inputs=loaded_graph.get_tensor_by_name(name='input:0')
    initial_state=loaded_graph.get_tensor_by_name(name='initial_state:0')
    final_state=loaded_graph.get_tensor_by_name(name='final_state:0')
    probs=loaded_graph.get_tensor_by_name(name='prob:0')
    
    return inputs, initial_state, final_state, probs

#test
#tests.test_get_tensors(get_tensors)

In [71]:
# select the next word using probabilities
"""
Pick the next word in the generated text
:param probabilities: Probabilites of the next word
:param int_to_vocab: Dictionary of word ids as the keys and words as the values
:return: String of the predicted word
"""
def pick_word(probabilities, int_to_vocab):
    idx=np.argmax(probabilities)
    return int_to_vocab[idx]

# test
tests.test_pick_word(pick_word)

Tests Passed


In [75]:
# Generate TV Scripts
gen_length=200
prime_word='moe_szyslak'

loaded_graph=tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    #load saved model
    loader=tf.train.import_meta_graph(load_dir+'.meta')
    loader.restore(sess, load_dir)
    
    #get tensors from loaded model
    input_text, initial_state, final_state, probs=get_tensors(loaded_graph)
    
    #sentence generation setup
    gen_sentences=[prime_word+':']
    prev_state=sess.run(initial_state, {input_text: np.array([[1]])})
    
    #generate sentences
    for n in range(gen_length):
        #dynamic input
        dyn_input=[[vocab_to_int[word] for word in gen_sentences[-seq_length:]]]
        dyn_seq_length=len(dyn_input[0])
        
        #get prediction
        probabilities, prev_state=sess.run([probs, final_state], {input_text: dyn_input, initial_state: prev_state})
        
        pred_word=pick_word(probabilities[dyn_seq_length-1], int_to_vocab)
        
        gen_sentences.append(pred_word)
    
    # Remove tokens
    tv_script = ' '.join(gen_sentences)
    for key, token in token_dict.items():
        ending = ' ' if key in ['\n', '(', '"'] else ''
        tv_script = tv_script.replace(' ' + token.lower(), key)
    tv_script = tv_script.replace('\n ', '\n')
    tv_script = tv_script.replace('( ', '(')
        
    print(tv_script)

moe_szyslak:(uneasy) oh, i gotta do that car?
homer_simpson:(looking around watch) see, you guys is a mister or more.
moe_szyslak:(sings) a-b- i don't wanna be a half more occurred to my face.
moe_szyslak:(incredulous) so one is a hundred woman baby!
moe_szyslak:(sighs) i see i was a good friend,(selling) but i did like you-- you know, i forgot a walk.
moe_szyslak:(embarrassed) i saved it, or the wrong guy.
moe_szyslak:(realizing) hey, you saved my wife, or me.
moe_szyslak:(sarcastic) oh, i don't know. i just wanted a rug." uh i got the alley."
homer_simpson:(panicky) oh, i need it, but i got a very way" good turns" / fixes the texas idea.
moe_szyslak:(delighted) playing for a little person?
moe_szyslak:(stunned) oh yeah, i can't admit you gonna see that one of my wife
